zookeeper:
  registry:
    address: 127.0.0.1:2181
    root-path: /clrpc
  discovery:
    address: 127.0.0.1:2181
    root-path: /clrpc
  monitor:
    address: 127.0.0.1:2181
    root-path: /clrpc
  atomicity:
    address: 127.0.0.1:2181
    root-path: /clrpc
  session:
    timeout: 5000 #ms

provider:
  port: 5100
  thread: # for netty
    boss: 1
    worker: 4
    
consumer:
  prot: 5200
  wait-time: 5000 #ms
  thread: # for netty
    worker: 4

service:
  thread-pool:
    core-size: 5
    max-size: 10
    keep-alive: 1000 #ms
    queue: 10
  cache:
    enable: false
