zookeeper:
  registry:
    address: localhost:2181
    root-path: /clrpc
  discovery:
    address: localhost:2181
    root-path: /clrpc
  monitor:
    address: localhost:2181
    root-path: /clrpc
  session:
    timeout: 5000 #ms

server:
  address: localhost:5100
  thread:
    boss: 1
    worker: 4
  request-receiver: conglin.clrpc.transfer.net.receiver.BasicRequestReceiver

client:
  address: localhost:5201
  session:
    timeout: 5000 #ms
  thread:
    worker: 4
  request-sender: conglin.clrpc.transfer.net.sender.BasicRequestSender

service:
  thread:
    pool:
      class: conglin.clrpc.common.util.threadpool.CustomizedThreadPool
      core-size: 5
      max-size: 10
      keep-alive: 1000 #ms
      queue: 10
  session:
    time-threshold: 5000 #ms
  codec:
    factory-class: conglin.clrpc.transfer.codec.protostuff.ProtostuffCodecFactory
