zookeeper:
  registry:
    url: localhost:2181
    root_path: /service/
  discovery:
    url: localhost:2181
    root_path: /service/
  session:
    timeout: 5000 #ms

server:
  url: localhost:5000
  thread:
    boss: 1
    worker: 4

client:
  connect-url:
    - localhost:5000
    # - localhost:5001
  session:
    timeout: 5000 #ms
  thread:
    worker: 4

service:
  thread:
    pool:
      class: conglin.clrpc.common.util.threadpool.FixedThreadPool
      core-size: 5
      max-size: 10
      keep-alive: 1000 #ms
      queue: 0
  session:
    time-threshold: 5000
