zookeeper:
  registry:
    address: localhost:2181
    root-path: /clrpc
  discovery:
    address: localhost:2181
    root-path: /clrpc
  monitor:
    address: localhost:2181
    root-path: /clrpc
  session:
    timeout: 5000 #ms

server:
  address: localhost:5000
  thread:
    boss: 1
    worker: 4

client:
  address: localhost:5200
  connect-address:
    - localhost:5000
    # - localhost:5001
  
  session:
    timeout: 5000 #ms
  thread:
    worker: 4

service:
  thread:
    pool:
      class: conglin.clrpc.common.util.threadpool.CustomizedThreadPool
      core-size: 5
      max-size: 10
      keep-alive: 1000 #ms
      queue: 10
  session:
    time-threshold: 5000 #ms
