zookeeper:
  registry:
    address: localhost:2181
    root-path: /clrpc
  discovery:
    address: localhost:2181
    root-path: /clrpc
  monitor:
    address: localhost:2181
    root-path: /clrpc
  session:
    timeout: 5000 #ms

provider:
  address: localhost:5100
  thread:
    boss: 1
    worker: 4
  response-sender: conglin.clrpc.transfer.sender.BasicResponseSender
  request-receiver: conglin.clrpc.transfer.receiver.BasicRequestReceiver

consumer:
  address: localhost:5200
  session:
    timeout: 5000 #ms
  thread:
    worker: 4
  request-sender: conglin.clrpc.transfer.sender.BasicRequestSender
  response-receiver: conglin.clrpc.transfer.receiver.BasicResponseReceiver

service:
  thread:
    pool:
      class: conglin.clrpc.common.util.threadpool.CustomizedThreadPool
      core-size: 5
      max-size: 10
      keep-alive: 1000 #ms
      queue: 10
  session:
    time-threshold: 5000 #ms
  codec:
    serialization-handler: conglin.clrpc.common.codec.protostuff.ProtostuffSerializationHandler
